language: java

before_install:
  - chmod a+x gradlew

jdk: openjdk11
sudo: false
env:
  - PORT=5000
script:
  - ./gradlew --console plain run &
  - cd src/test/acceptanceTests
  - bundle install
  - bundle exec spinach
  - kill %1